version: "3.8"
services:
  database:
    image: mongo:latest
    container_name: database
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=articles
    volumes:
      - ./infra/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  articles:
    container_name: article-keeper
    restart: on-failure
    depends_on:
      - database
    build: .
    ports:
      - "8080:8080"
    environment:
      - FEED_API_URL=https://www.htafc.com/api/incrowd/
      - POLL_INTERVAL=1m
      - STORAGE_DB_NAME=articles
      - STORAGE_URI=mongodb://database:27017/articles
